// Generated by @supabase/supabase-js DO NOT EDIT
// This file is a generated type definition
// Manual changes will be lost if regenerated

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string
          name: string
          slug: string | null
          address: string | null
          phone: string | null
          email: string | null
          logo_url: string | null
          mercadopago_pos_external_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug?: string | null
          address?: string | null
          phone?: string | null
          email?: string | null
          logo_url?: string | null
          mercadopago_pos_external_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string | null
          address?: string | null
          phone?: string | null
          email?: string | null
          logo_url?: string | null
          mercadopago_pos_external_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      business_mercadopago_access: {
        Row: {
          business_id: string
          access_token: string | null
          updated_at: string
        }
        Insert: {
          business_id: string
          access_token?: string | null
          updated_at?: string
        }
        Update: {
          business_id?: string
          access_token?: string | null
          updated_at?: string
        }
      }
      business_payment_methods: {
        Row: {
          id: string
          business_id: string
          method_code: string
          label: string
          icon_key: string
          icon_url: string | null
          is_active: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          method_code: string
          label: string
          icon_key?: string
          icon_url?: string | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          method_code?: string
          label?: string
          icon_key?: string
          icon_url?: string | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      memberships: {
        Row: {
          business_id: string
          user_id: string
          role: string
          permissions: Json
          deleted_at: string | null
          deleted_by: string | null
          created_at: string
        }
        Insert: {
          business_id: string
          user_id: string
          role?: string
          permissions?: Json
          deleted_at?: string | null
          deleted_by?: string | null
          created_at?: string
        }
        Update: {
          business_id?: string
          user_id?: string
          role?: string
          permissions?: Json
          deleted_at?: string | null
          deleted_by?: string | null
          created_at?: string
        }
      }
      products: {
        Row: {
          id: string
          business_id: string
          name: string
          sku: string | null
          barcode: string | null
          scale_code: string | null
          category: string | null
          price: number
          cost: number | null
          sold_by_weight: boolean
          stock: number
          stock_decimal: number
          active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          sku?: string | null
          barcode?: string | null
          scale_code?: string | null
          category?: string | null
          price?: number
          cost?: number | null
          sold_by_weight?: boolean
          stock?: number
          stock_decimal?: number
          active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          sku?: string | null
          barcode?: string | null
          scale_code?: string | null
          category?: string | null
          price?: number
          cost?: number | null
          sold_by_weight?: boolean
          stock?: number
          stock_decimal?: number
          active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      sales: {
        Row: {
          id: string
          business_id: string
          cashier_user_id: string | null
          cash_register_id: string | null
          total: number
          payment_method: string
          payment_details: Json | null
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          cashier_user_id?: string | null
          cash_register_id?: string | null
          total?: number
          payment_method: string
          payment_details?: Json | null
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          cashier_user_id?: string | null
          cash_register_id?: string | null
          total?: number
          payment_method?: string
          payment_details?: Json | null
          status?: string
          created_at?: string
          updated_at?: string
        }
      }
      sale_items: {
        Row: {
          id: string
          business_id: string
          sale_id: string
          product_id: string
          name: string
          quantity: number
          unit_price: number
          total: number
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          sale_id: string
          product_id: string
          name: string
          quantity: number
          unit_price: number
          total: number
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          sale_id?: string
          product_id?: string
          name?: string
          quantity?: number
          unit_price?: number
          total?: number
          created_at?: string
        }
      }
      cash_registers: {
        Row: {
          id: string
          business_id: string
          opened_by: string | null
          closed_by: string | null
          opened_at: string
          closed_at: string | null
          opening_amount: number
          closing_amount: number | null
          shift_start_at: string | null
          shift_end_at: string | null
          notes: string | null
          expected_totals: Json | null
          closing_totals: Json | null
          difference_totals: Json | null
        }
        Insert: {
          id?: string
          business_id: string
          opened_by?: string | null
          closed_by?: string | null
          opened_at?: string
          closed_at?: string | null
          opening_amount?: number
          closing_amount?: number | null
          shift_start_at?: string | null
          shift_end_at?: string | null
          notes?: string | null
          expected_totals?: Json | null
          closing_totals?: Json | null
          difference_totals?: Json | null
        }
        Update: {
          id?: string
          business_id?: string
          opened_by?: string | null
          closed_by?: string | null
          opened_at?: string
          closed_at?: string | null
          opening_amount?: number
          closing_amount?: number | null
          shift_start_at?: string | null
          shift_end_at?: string | null
          notes?: string | null
          expected_totals?: Json | null
          closing_totals?: Json | null
          difference_totals?: Json | null
        }
      }
      cash_movements: {
        Row: {
          id: string
          business_id: string
          cash_register_id: string | null
          movement_type: string
          payment_method: string
          amount: number
          reason: string
          notes: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          cash_register_id?: string | null
          movement_type: string
          payment_method: string
          amount: number
          reason: string
          notes?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          cash_register_id?: string | null
          movement_type?: string
          payment_method?: string
          amount?: number
          reason?: string
          notes?: string | null
          created_by?: string | null
          created_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          business_id: string
          status: string
          plan_id: string | null
          current_period_start: string | null
          current_period_end: string | null
          cancel_at_period_end: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          status: string
          plan_id?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          status?: string
          plan_id?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}