import Image from "next/image";
import type { MouseEvent } from "react";
import { Handshake } from "lucide-react";
import { trackFunnelEvent } from "@/lib/leads/analytics";

export function LandingHero({ onStoreClick, storeUrl, certificateStoreUrl, marketplaceUrl }: { onStoreClick: (event: MouseEvent<HTMLAnchorElement>, location: string) => void; storeUrl: string; certificateStoreUrl: string; marketplaceUrl: string }) {
  const toDemo = () => { trackFunnelEvent("hero_cta_click"); document.querySelector("#demo")?.scrollIntoView({ behavior: "smooth" }); };
  return <section className="t360-hero"><div className="t360-wrap t360-hero-grid">
    <div><p className="t360-kicker">Punto de venta para Windows · Argentina</p><h1>Convertí tu PC en un <em>punto de venta completo</em></h1><p className="t360-lead">Vendé más rápido, controlá stock, caja y facturación desde un solo lugar.</p>
      <div className="t360-hero-ctas"><div className="t360-try-block"><p className="t360-action-label">Probalo gratis por 3 días</p><div className="t360-actions"><a className="t360-store-button" href={storeUrl} target="_blank" rel="noopener noreferrer" onClick={(event) => onStoreClick(event, "hero")} aria-label="Descargar Tienda360 desde Microsoft Store (abre en una pestaña nueva)"><span className="t360-windows-mark" aria-hidden="true"><i /><i /><i /><i /></span><span><small>Descargar prueba desde</small><b>Microsoft Store</b></span><span className="t360-store-arrow" aria-hidden="true">↗</span></a><button className="t360-button t360-button-ghost" onClick={toDemo}>▶ Mirar la demo</button></div><p className="t360-store-note"><span aria-hidden="true">✓</span> Solo para PC con Windows 10/11 · No necesitás tarjeta</p></div><div className="t360-buy-block"><div><small>¿Ya lo probaste?</small><b>Comprá la licencia definitiva</b></div><a className="t360-button t360-hero-marketplace" href={marketplaceUrl} target="_blank" rel="noopener noreferrer" onClick={() => trackFunnelEvent("mercadolibre_clicked", { location: "hero" })} aria-label="Comprar la licencia definitiva de Tienda360 en Mercado Libre (abre en una pestaña nueva)"><span className="t360-mercadolibre-logo" aria-hidden="true"><Handshake /></span><span>Comprar en Mercado Libre</span><span aria-hidden="true">↗</span></a></div></div>
      <ul className="t360-checks"><li>350.000 productos precargados</li><li>Facturación electrónica ARCA</li><li>Cobros con QR</li><li>Control de stock y caja</li><li>Lectores de códigos de barras</li><li>Soporte y actualizaciones</li></ul>
    </div><div className="t360-hero-visual"><Image src="/landing.png" alt="Tienda360: punto de venta para comercios, disponible con prueba gratuita" width={1260} height={1260} priority sizes="(max-width: 900px) 100vw, 48vw" style={{ width: "100%", height: "auto", objectFit: "contain" }} /><a className="t360-microsoft-certificate" href={certificateStoreUrl} target="_blank" rel="noopener noreferrer" onClick={(event) => onStoreClick(event, "hero_certificate")} aria-label="Tienda360, aplicación certificada. Ver en Microsoft Store (abre en una pestaña nueva)"><Image src="/Insignia%20de%20aplicaci%C3%B3n%20Microsoft%20certificada.png" alt="Insignia de aplicación Microsoft certificada" width={1536} height={1024} sizes="(max-width: 600px) 160px, 210px" /></a><span>Probalo gratis durante 3 días en tu comercio</span></div>
  </div></section>;
}

