import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Banknote, Barcode, BarChart3, Boxes, Check, CreditCard, ExternalLink, GraduationCap, Headphones, LogIn, MapPinned, Percent, Quote, ReceiptText, ShieldCheck, ShoppingCart, Star, Truck } from "lucide-react";
import { MetaPixel } from "@/components/analytics/meta-pixel";
import { MetaTrackedLink } from "@/components/analytics/meta-tracked-link";
import { LandingAbout } from "@/components/landing/LandingAbout";
import { LandingVideoTutorials } from "@/components/landing/LandingVideoTutorials";
import { formatStorePrice, getStoreProductBySku } from "@/lib/store-products";
import comboImage from "@/combo250.png";

const features = [
  { icon: Barcode, title: "+300.000 productos", text: "Empezá a vender desde el primer día con productos precargados." },
  { icon: BarChart3, title: "Reportes completos", text: "Conocé ventas, ganancias y tus productos más vendidos." },
  { icon: Boxes, title: "Control de stock", text: "Sabé qué tenés, qué falta y evitá pérdidas." },
  { icon: Percent, title: "Promociones", text: "Creá descuentos, ofertas y combos fácilmente." },
  { icon: ReceiptText, title: "Caja diaria", text: "Apertura, cierre, arqueo y movimientos de caja." },
  { icon: ShieldCheck, title: "Facturación con ARCA", text: "Emití Factura C y tickets desde el sistema." },
];

const googleReviewsUrl = "https://share.google/BPWagGBYz3I2aQEbU";
const googleReviews = [
  { name: "Natalia Porto", text: "Calidad humana y profesional!" },
  { name: "Agustina Scoppa", text: "Excelente atención, antes y después de la compra!" },
];

export default async function Home({ searchParams }: { searchParams?: Promise<{ missingSupabase?: string }> }) {
  const sp = (await searchParams) ?? {};
  const product = await getStoreProductBySku("combo_essential");
  const price = product?.price_ars ?? 250_000;
  const cashPrice = Math.round(price * 0.9);
  const installmentPrice = Math.round(price / 3);
  return <main className="overflow-hidden bg-[#f4f7fb] text-slate-950">
    <MetaPixel />
    {sp.missingSupabase ? <div className="border-b border-amber-300 bg-amber-100 px-4 py-3 text-center text-sm">La recepción de pedidos está momentáneamente en mantenimiento.</div> : null}
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#061b3f]/95 text-white backdrop-blur-xl"><div className="mx-auto flex h-17 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-12">
      <a href="#inicio" className="flex items-center gap-2 text-lg font-black"><span className="grid size-9 place-items-center rounded-xl bg-[#ffd400] text-[#061b3f]"><ShoppingCart className="size-5" /></span>tienda<span className="-ml-2 text-sky-400">360</span></a>
      <nav className="hidden gap-7 text-sm font-semibold text-white/70 md:flex"><a href="#incluye">Qué incluye</a><a href="#entrega">Entrega</a><a href="#tutoriales">Videos</a><a href="#resenas">Reseñas</a><a href="#nosotros">Nosotros</a><a href="#preguntas">Preguntas</a></nav>
      <div className="flex items-center gap-2">
        <Link href="/auth/login" className="inline-flex h-10 items-center rounded-full border border-white/25 bg-white/10 px-3 text-sm font-bold text-white transition hover:bg-white/20 sm:px-4"><LogIn className="size-4 sm:mr-2" /><span className="hidden sm:inline">Ingresar al sistema</span><span className="sr-only sm:hidden">Ingresar al sistema</span></Link>
        <a href="#comprar" className="inline-flex h-10 items-center rounded-full bg-[#ffd400] px-3 text-sm font-black text-[#061b3f] sm:px-4"><span className="sm:hidden">Comprar</span><span className="hidden sm:inline">Comprar combo</span><ArrowRight className="ml-1.5 size-4" /></a>
      </div>
    </div></header>

    <section id="inicio" className="relative bg-[radial-gradient(circle_at_75%_35%,#0b65c8_0%,#062859_38%,#04152f_72%)] py-16 text-white sm:py-24"><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(255,255,255,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.08)_1px,transparent_1px)] [background-size:44px_44px]" /><div className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:px-12">
      <div><p className="inline-flex items-center gap-2 rounded-full border border-[#ffd400]/40 bg-[#ffd400]/10 px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-[#ffe869]"><BadgeCheck className="size-4" /> Todo para vender mejor</p><h1 className="mt-6 text-5xl font-black leading-[.95] tracking-[-.055em] sm:text-7xl">El combo completo para <span className="text-sky-400">tu comercio</span></h1><p className="mt-6 max-w-xl text-lg font-semibold leading-8 text-white/75">Software Tienda360 con licencia de por vida, lector inalámbrico e impresora térmica. Sin suscripciones ni pagos mensuales.</p>
      <div className="mt-7 flex flex-wrap items-center gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-red-300">Precio del combo</p><p className="text-5xl font-black">{formatStorePrice(price)}</p></div><span className="rounded-xl bg-red-600 px-4 py-3 text-center text-sm font-black">LICENCIA<br />DE POR VIDA</span></div>
      <div className="mt-6 grid max-w-xl gap-3 sm:grid-cols-2">
        <div className="relative overflow-hidden rounded-2xl border border-emerald-300/40 bg-emerald-400/15 p-4"><div className="absolute -right-5 -top-5 size-20 rounded-full bg-emerald-300/15" /><div className="relative flex items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-emerald-400 text-emerald-950"><Banknote className="size-6" /></span><div><p className="text-xs font-black uppercase tracking-wide text-emerald-300">10% de descuento</p><p className="text-xl font-black">{formatStorePrice(cashPrice)}</p><p className="text-xs text-white/65">Efectivo o transferencia</p></div></div></div>
        <div className="relative overflow-hidden rounded-2xl border border-fuchsia-300/40 bg-fuchsia-400/15 p-4"><div className="absolute -right-5 -top-5 size-20 rounded-full bg-fuchsia-300/15" /><div className="relative flex items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-fuchsia-400 text-fuchsia-950"><CreditCard className="size-6" /></span><div><p className="text-xs font-black uppercase tracking-wide text-fuchsia-300">3 cuotas sin interés</p><p className="text-xl font-black">{formatStorePrice(installmentPrice)}</p><p className="text-xs text-white/65">Con tarjetas habilitadas</p></div></div></div>
      </div>
      <a href="#comprar" className="mt-6 inline-flex min-h-14 items-center rounded-xl bg-[#ffd400] px-7 text-sm font-black text-[#061b3f] shadow-xl">ELEGIR ENTREGA Y COMPRAR <ArrowRight className="ml-2 size-5" /></a><div className="mt-6 flex flex-wrap gap-5 text-xs font-semibold text-white/65"><span>✓ Pago seguro</span><span>✓ Envío gratis</span><span>✓ Capacitación incluida</span></div></div>
      <div className="relative"><div className="absolute inset-10 rounded-full bg-sky-400/25 blur-3xl" /><Image src={comboImage} alt="Combo Tienda360 con software, lector inalámbrico e impresora térmica" className="relative h-auto w-full object-contain drop-shadow-[0_28px_35px_rgba(0,0,0,.35)]" priority sizes="(max-width: 1024px) 100vw, 55vw" /><div className="absolute bottom-2 left-2 rounded-2xl bg-white/95 px-4 py-3 text-[#061b3f] shadow-xl"><p className="text-xs font-bold text-slate-500">Incluye</p><p className="text-sm font-black">Software + lector + impresora</p></div></div>
    </div></section>

    <section id="incluye" className="py-18 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-700">Todo en una sola compra</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Tu negocio listo para trabajar</h2><p className="mt-4 text-slate-600">Conectás el lector y la impresora, instalamos Tienda360 y ya podés empezar a vender.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(({icon:Icon,title,text}) => <article key={title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-700"><Icon className="size-6" /></span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

    <section id="comprar" className="bg-[#061b3f] py-18 text-white sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ffd400]">Elegí según tu ubicación</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">¿Dónde instalamos tu combo?</h2><p className="mt-4 text-white/65">Guardamos tus datos para acompañar cada pedido.</p></div><div id="entrega" className="mt-10 grid gap-6 lg:grid-cols-2">
      <article className="rounded-[2rem] border border-emerald-300/30 bg-emerald-400/10 p-7 sm:p-9"><span className="grid size-14 place-items-center rounded-2xl bg-emerald-400 text-emerald-950"><MapPinned className="size-7" /></span><p className="mt-6 text-xs font-black uppercase tracking-[.18em] text-emerald-300">CABA y AMBA</p><h3 className="mt-2 text-3xl font-black">Instalación y capacitación gratis</h3><p className="mt-4 leading-7 text-white/70">Elegí pagar online ahora o dejarnos tus datos para coordinar la visita, la entrega y la forma de pago.</p><ul className="mt-6 grid gap-3 text-sm font-semibold">{["10% OFF en efectivo o transferencia","También podés pagar online con Mercado Pago","Instalación y capacitación sin cargo"].map(x=><li key={x} className="flex gap-2"><Check className="size-5 text-emerald-300" />{x}</li>)}</ul><div className="mt-8 grid gap-3 sm:grid-cols-2"><Link href="/reservar/combo_essential" className="inline-flex min-h-13 items-center justify-center rounded-xl border border-emerald-300 bg-emerald-950/30 px-4 text-center text-sm font-black text-emerald-200">COORDINAR PAGO</Link><Link href="/comprar/combo_essential?delivery=local" className="inline-flex min-h-13 items-center justify-center rounded-xl bg-emerald-400 px-4 text-center text-sm font-black text-emerald-950">PAGAR ONLINE <ArrowRight className="ml-2 size-4" /></Link></div></article>
      <article className="rounded-[2rem] border border-sky-300/30 bg-sky-400/10 p-7 sm:p-9"><span className="grid size-14 place-items-center rounded-2xl bg-sky-400 text-[#061b3f]"><Truck className="size-7" /></span><p className="mt-6 text-xs font-black uppercase tracking-[.18em] text-sky-300">Interior del país</p><h3 className="mt-2 text-3xl font-black">Comprá online y recibilo gratis</h3><p className="mt-4 leading-7 text-white/70">Completá los datos de envío y pagá online. Generamos tu número de pedido para seguir la preparación y el despacho.</p><ul className="mt-6 grid gap-3 text-sm font-semibold">{["Envío gratis por Correo Argentino","Pago seguro con Mercado Pago","Número y seguimiento de pedido"].map(x=><li key={x} className="flex gap-2"><Check className="size-5 text-sky-300" />{x}</li>)}</ul><Link href="/comprar/combo_essential" className="mt-8 inline-flex min-h-13 w-full items-center justify-center rounded-xl bg-[#ffd400] px-5 text-sm font-black text-[#061b3f]">COMPRAR POR {formatStorePrice(price)} <ArrowRight className="ml-2 size-4" /></Link></article>
    </div></div></section>

    <section className="bg-white py-14"><div className="mx-auto grid max-w-7xl gap-5 px-5 sm:grid-cols-3 sm:px-8 lg:px-12">{[[ShieldCheck,"Garantía 12 meses","En lector e impresora."],[Headphones,"Soporte permanente","Te acompañamos siempre."],[GraduationCap,"Capacitación incluida","Te enseñamos a usarlo."]].map(([Icon,title,text]) => { const I=Icon as typeof ShieldCheck; return <div key={String(title)} className="flex gap-4 rounded-2xl border p-5"><I className="size-6 text-blue-700"/><div><h3 className="font-black">{String(title)}</h3><p className="text-sm text-slate-600">{String(text)}</p></div></div>})}</div></section>
    <section className="mx-auto max-w-7xl px-5 py-18 sm:px-8 sm:py-24 lg:px-12"><LandingVideoTutorials /><LandingAbout /></section>
    <section id="resenas" className="bg-white py-18 sm:py-24" aria-labelledby="reviews-title"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="grid items-center gap-8 lg:grid-cols-[.72fr_1.28fr]">
      <div className="rounded-[2rem] bg-[#061b3f] p-8 text-white shadow-xl sm:p-10"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ffd400]">Opiniones en Google</p><h2 id="reviews-title" className="mt-3 text-4xl font-black">Quienes nos eligen nos recomiendan</h2><div className="mt-7 flex items-end gap-3"><strong className="text-6xl font-black">5,0</strong><div className="pb-1"><div className="flex gap-1 text-[#ffd400]" aria-label="5 de 5 estrellas">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-5 fill-current" />)}</div><p className="mt-1 text-sm text-white/65">6 opiniones en Google</p></div></div><a href={googleReviewsUrl} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex min-h-12 items-center justify-center rounded-xl bg-[#ffd400] px-5 text-sm font-black text-[#061b3f]">VER TODAS EN GOOGLE <ExternalLink className="ml-2 size-4" /></a></div>
      <div className="grid gap-4 sm:grid-cols-2">{googleReviews.map((review)=><article key={review.name} className="relative rounded-3xl border border-slate-200 bg-[#f7f9fc] p-7 shadow-sm"><Quote className="size-9 text-sky-200" aria-hidden /><div className="mt-5 flex gap-1 text-amber-500">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-4 fill-current" />)}</div><blockquote className="mt-4 text-lg font-bold leading-8 text-slate-900">“{review.text}”</blockquote><p className="mt-6 text-sm font-black text-slate-700">{review.name}</p><p className="mt-1 text-xs text-slate-500">Reseña publicada en Google</p></article>)}</div>
    </div></div></section>
    <section id="preguntas" className="py-18 sm:py-24"><div className="mx-auto max-w-4xl px-5"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-700">Sin letra chica</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Preguntas frecuentes</h2></div><div className="mt-10 divide-y divide-slate-200 rounded-[2rem] border border-slate-200 bg-white px-5 sm:px-8">{[
      ["¿Cuánto cuesta el combo?",`El precio es de ${formatStorePrice(price)}. Pagando en efectivo o por transferencia tenés 10% de descuento y queda en ${formatStorePrice(cashPrice)}. También podés elegir 3 cuotas sin interés de ${formatStorePrice(installmentPrice)} con tarjetas habilitadas.`],
      ["¿Tengo que pagar todos los meses?","No. Tienda360 incluye una licencia de por vida, sin suscripciones ni pagos mensuales."],
      ["¿Qué incluye exactamente el combo?","Incluye el software de gestión Tienda360, un lector de códigos de barras inalámbrico y una impresora térmica para tickets."],
      ["¿Funciona en celular?","El sistema se utiliza en una PC con Windows. Sí podés completar la compra desde tu celular y luego coordinamos la instalación en la computadora del comercio."],
      ["¿Qué Windows necesito?","Una PC con Windows 10 o Windows 11 de 64 bits y conexión a internet para la activación y las funciones online."],
      ["¿La instalación en CABA y AMBA tiene costo?","No. Coordinamos la entrega, la instalación y una capacitación inicial en tu comercio sin cargo adicional."],
      ["¿Cómo compro si estoy en CABA o AMBA?","Dejanos tus datos y la dirección del comercio. Te contactamos por WhatsApp para confirmar la zona, coordinar la visita y acordar la forma de pago."],
      ["¿Cómo recibo el combo en el interior?","Completás tus datos de envío, pagás online mediante Mercado Pago y despachamos el combo gratis por Correo Argentino."],
      ["¿Recibo un número de pedido?","Sí. Después de confirmar la compra te mostramos un número de pedido y podés consultar el estado de preparación y envío."],
      ["¿Cómo puedo pagar?","Podés pagar en efectivo o por transferencia con 10% de descuento. También ofrecemos 3 cuotas sin interés con tarjetas habilitadas. Para envíos al interior, el pago online se procesa de forma segura mediante Mercado Pago."],
      ["¿Tengo soporte técnico?","Sí. Contás con soporte para la instalación, configuración inicial y consultas sobre el uso de Tienda360."],
      ["¿Tiene integración con ARCA?","Sí. Tienda360 permite configurar la facturación con ARCA. Necesitás acceso a tu cuenta, un punto de venta y el certificado correspondiente; podemos acompañarte durante la configuración."],
      ["¿Puedo usarlo en varias PC conectadas en red?","Esta licencia está preparada para utilizar Tienda360 de manera local en una sola PC."],
      ["¿Sirve para mi rubro?","Sí. Tiene modos para retail, indumentaria y gastronomía, y se adapta a kioscos, almacenes, autoservicios, pet shops, ferreterías y otros comercios."],
      ["¿Necesito conocimientos de informática?","No. Está pensado para ser simple e intuitivo. Además, la capacitación inicial te ayuda a empezar con seguridad."],
    ].map(([q,a])=><details key={q} className="group py-5"><summary className="cursor-pointer list-none pr-8 font-black marker:hidden">{q}<span className="float-right text-2xl text-blue-700 transition group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{a}</p></details>)}</div></div></section>
    <footer className="bg-[#04152f] text-white/60"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-10 text-sm sm:flex-row sm:justify-between"><p className="font-black text-white">tienda<span className="text-sky-400">360</span></p><div className="flex gap-5"><MetaTrackedLink event="ClickWhatsApp" href="https://wa.me/5491123145742">WhatsApp</MetaTrackedLink><Link href="/pedido">Seguir pedido</Link><Link href="/auth/login">Ingresar</Link></div></div></footer>
  </main>;
}
