import Link from "next/link";
import { Search } from "lucide-react";
import { updateLeadStatus } from "./actions";
import { createAdminClient } from "@/lib/supabase/admin";
import { LEAD_STATUSES } from "@/lib/leads/types";
export const dynamic = "force-dynamic";
type Row = { id:string;created_at:string;full_name:string;whatsapp:string;locality:string;business_type:string;pc_status:string;reader_status:string;intent:string;classification:string;scheduled_at:string|null;status:string };
const FILTERS = [["all","Todos"],["high","Alta intención"],["today","Agendados hoy"],["pending","Pendientes"],["trial","En prueba"],["active","Activados"],["lost","No interesados"]] as const;
function localDay(v:string){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Argentina/Buenos_Aires",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(v))}
function intentLabel(v:string){return ({implement:"Implementar",replace:"Reemplazar sistema",learn:"Conocer",browsing:"Averiguando"} as Record<string,string>)[v]??v}
export default async function LeadsPage({searchParams}:{searchParams:Promise<{filter?:string;q?:string}>}){
  const {filter="all",q=""}=await searchParams;
  const {data,error}=await createAdminClient().from("qualified_leads").select("id,created_at,full_name,whatsapp,locality,business_type,pc_status,reader_status,intent,classification,scheduled_at,status").order("created_at",{ascending:false}).limit(1000);
  if(error)return <div className="m-5 rounded-2xl border border-amber-500/30 bg-amber-500/5 p-6"><h1 className="text-2xl font-bold">Leads calificados</h1><p className="mt-2 text-sm text-muted-foreground">Aplicá la migración <code>20261002120000_qualified_leads_and_schedule.sql</code>.</p><p className="mt-2 text-xs">{error.message}</p></div>;
  const today=localDay(new Date().toISOString()),needle=q.trim().toLowerCase();
  const rows=(data as Row[]).filter(r=>(!needle||`${r.full_name} ${r.whatsapp}`.toLowerCase().includes(needle))&&(filter==="all"||filter==="high"&&r.classification==="ALTA INTENCIÓN"||filter==="today"&&!!r.scheduled_at&&localDay(r.scheduled_at)===today||filter==="pending"&&["NUEVO","CALIFICADO","AGENDADO"].includes(r.status)||filter==="trial"&&r.status==="EN PRUEBA"||filter==="active"&&r.status==="ACTIVADO"||filter==="lost"&&r.status==="NO INTERESADO"));
  return <div className="mx-auto w-full max-w-[1500px] space-y-5 px-4 py-8">
    <div><p className="text-xs font-semibold uppercase tracking-wider text-orange-500">Embudo comercial</p><h1 className="mt-1 text-3xl font-bold">Leads calificados</h1><p className="mt-2 text-sm text-muted-foreground">Priorizá intención, turno y próximo estado comercial.</p></div>
    <div className="flex flex-wrap gap-2">{FILTERS.map(([key,label])=><Link key={key} href={`/admin/leads?filter=${key}${q?`&q=${encodeURIComponent(q)}`:""}`} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${filter===key?"border-orange-500 bg-orange-500/10 text-orange-600":"border-[var(--pos-border)]"}`}>{label}</Link>)}</div>
    <form className="flex max-w-md items-center gap-2"><input type="hidden" name="filter" value={filter}/><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><input name="q" defaultValue={q} placeholder="Buscar por nombre o WhatsApp" className="h-10 w-full rounded-lg border bg-background pl-9 pr-3 text-sm"/></div><button className="h-10 rounded-lg bg-foreground px-4 text-sm font-semibold text-background">Buscar</button></form>
    <div className="overflow-x-auto rounded-2xl border border-[var(--pos-border)] bg-[var(--pos-surface)]"><table className="w-full min-w-[1320px] text-left text-xs"><thead className="bg-[var(--pos-surface-2)] text-muted-foreground"><tr>{["Fecha","Nombre","WhatsApp","Rubro","PC","Lector","Intención","Clasificación","Turno","Estado"].map(x=><th className="px-3 py-3 uppercase tracking-wide" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t border-[var(--pos-border)]" key={r.id}>
      <td className="px-3 py-3">{new Date(r.created_at).toLocaleDateString("es-AR")}</td><td className="px-3 py-3"><b>{r.full_name}</b><br/><span className="text-muted-foreground">{r.locality}</span></td><td className="px-3 py-3"><a className="text-emerald-600 underline" href={`https://wa.me/${r.whatsapp}`} target="_blank" rel="noreferrer">+{r.whatsapp}</a></td><td className="px-3 py-3">{r.business_type}</td><td className="px-3 py-3">{r.pc_status}</td><td className="px-3 py-3">{r.reader_status}</td><td className="px-3 py-3">{intentLabel(r.intent)}</td>
      <td className="px-3 py-3"><span className={`rounded-full px-2 py-1 font-bold ${r.classification.startsWith("ALTA")?"bg-emerald-500/15 text-emerald-700":r.classification.startsWith("MEDIA")?"bg-amber-500/15 text-amber-700":"bg-muted text-muted-foreground"}`}>{r.classification}</span></td><td className="px-3 py-3">{r.scheduled_at?new Date(r.scheduled_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires",dateStyle:"short",timeStyle:"short"}):"—"}</td>
      <td className="px-3 py-3"><form action={updateLeadStatus} className="flex gap-1"><input type="hidden" name="id" value={r.id}/><select name="status" defaultValue={r.status} className="rounded-md border bg-background px-2 py-1.5">{LEAD_STATUSES.map(s=><option key={s}>{s}</option>)}</select><button className="rounded-md border px-2 font-semibold">Guardar</button></form></td>
    </tr>)}</tbody></table>{rows.length===0&&<p className="p-10 text-center text-sm text-muted-foreground">No hay leads para este filtro.</p>}</div>
  </div>;
}
